"""The library, grouped: sixteen families of maps that look alike.

The colormap library is seven hundred maps and a reader cannot hold that. A
figure of it needs a *shorthand* — a small number of groups, each shown by a few
members that stand for the rest — and this is where that shorthand comes from.

It is **not** the source project's flavour taxonomy. That was an artifact
computed over a library this repository holds a subset of, and it does not
transfer; see [`fractal_wallpapers.palettes.space`], which brought the property
across instead of the table. This is computed here, from the tracked library
alone, by a stated method, and regenerating it is a subcommand.

## The method, stated

**Ward's agglomerative linkage over [`space.distances`], cut at sixteen
clusters.** Every step of that is a decision:

* The **metric** is palette space: thirty-two samples of the gradient *as the
  renderer spends it* — folded where the map is sequential — converted to Oklab.
  The same metric a candidate set is drawn in, so a cluster and a candidate set
  mean the same kind of "alike".
* **Ward** rather than single or average linkage because the question is "what
  are the families", and Ward is the criterion that minimizes within-group
  variance at every merge. Single linkage answers a different question and
  answers it by chaining half the library into one group.
* **Sixteen** because that is the size a figure can label. It is a reading of
  the library, not a discovery about it: nothing downstream reads this file, and
  no threshold was fitted to choose the number.

The linkage runs on the distance matrix **rounded to twelve decimals**. Ward
merges the closest pair at every step, and two pairs whose distances agree to the
fifteenth digit would otherwise merge in whichever order the platform's linear
algebra happened to produce — the matrix is built through a Gram product, and
that is not bit-identical across BLAS implementations. Rounding first turns a
platform difference into an exact tie, and an exact tie is broken by index, so
the clustering is a function of the library and nothing else. That is what lets
`tests/test_palette_clusters.py` hold the committed file to regeneration.

## The five most central maps

A cluster's shorthand is its **medoids**: the five members with the smallest mean
distance to the rest of their own cluster, ties broken by name. The centre of a
group of gradients is a gradient somebody can look at, which the mean of thirty-two
Oklab samples is not.
"""

from __future__ import annotations

import json
from pathlib import Path

from fractal_wallpapers.paths import colormap_dir

#: The schema this record carries, from its first line.
SCHEMA = 1

#: What the file is called, beside the maps it groups. JSONL rather than JSON,
#: and that is not a style choice: every reader of the colormap library globs
#: `data/palettes/*.json` and takes the stem as a map name, so a `.json` file in
#: there that is not a colormap would be read as one by the pool, the cyclic
#: table and this module's own [`library`].
RECORD_NAME = "clusters.jsonl"

#: The two kinds of row the record holds. One header, then one row per cluster —
#: the shape the walk's own ledger uses, for the same reason: a file whose rows
#: differ says so on every row rather than by position.
METHOD_ROW = "method"
CLUSTER_ROW = "cluster"

#: How many groups the tree is cut into.
CLUSTERS = 16

#: How many members stand for a cluster in the figure.
CENTRAL = 5

#: Decimals the distance matrix is rounded to before linkage. See the module
#: docstring: this is what makes the merge order platform-independent.
PLACES = 12

#: The method, carried in the file so a reader never has to find this module.
METHOD = (
    "Ward's agglomerative linkage over palettes.space.distances — 32 samples of each "
    "gradient as the renderer spends it (folded where the map is sequential), converted "
    "to Oklab, Euclidean over the resulting 96 numbers — cut at "
    f"{CLUSTERS} clusters. The distance matrix is rounded to {PLACES} decimals before "
    "linkage so the merge order does not depend on the platform's linear algebra, and "
    "exact ties merge in index order. Each cluster's `central` names are its medoids: "
    f"the {CENTRAL} members with the smallest mean distance to the rest of their own "
    "cluster, ties broken by name. Nothing downstream reads this file; it is a reading "
    "of the library for a figure, regenerated by `fractal-wallpapers palettes clusters`."
)


class ClusterError(RuntimeError):
    """The library cannot be grouped."""


def library(directory: Path | None = None) -> list[str]:
    """Every tracked map, by name, in sorted order."""
    directory = Path(directory) if directory is not None else colormap_dir()
    return sorted(path.stem for path in directory.glob("*.json"))


def ward(matrix, count: int) -> list[list[int]]:
    """Ward's linkage over a distance matrix, stopped at `count` groups.

    The Lance-Williams update in distance space, which is the same recurrence
    `scipy`'s `ward` uses:

    ```text
    d(i∪j, k) = sqrt( ((nᵢ+n_k)·d²ᵢₖ + (nⱼ+n_k)·d²ⱼₖ − n_k·d²ᵢⱼ) / (nᵢ+nⱼ+n_k) )
    ```

    Returns the groups as lists of row indices, each sorted, the groups
    themselves ordered by their smallest member — so the numbering is a function
    of the input and not of the order the merges happened to happen in.
    """
    import numpy

    size = len(matrix)
    if count < 1 or count > size:
        raise ClusterError(f"cannot cut {size} maps into {count} clusters")
    distance = numpy.array(matrix, dtype=numpy.float64)
    numpy.fill_diagonal(distance, numpy.inf)
    members = {index: [index] for index in range(size)}
    weight = numpy.ones(size, dtype=numpy.float64)
    alive = numpy.ones(size, dtype=bool)

    while len(members) > count:
        # The closest surviving pair. `argmin` over a matrix whose dead rows and
        # whose diagonal are `inf` picks it, and it picks the lowest flat index
        # among equals — which is the lowest `(i, j)`, so a tie is broken by
        # index rather than by whatever order the merges reached it in.
        flat = int(numpy.argmin(distance))
        first, second = divmod(flat, size)
        if first > second:
            first, second = second, first

        left, right = weight[first], weight[second]
        joined = left + right
        # The whole recurrence in one vectorized step, over every surviving `k`
        # at once, off the two merging rows rather than off a squared copy of the
        # matrix — which at seven hundred maps is the difference between a second
        # and a minute. `maximum(..., 0)` guards the square root against a
        # difference that rounding took a hair below zero on a coincident pair.
        to_first = distance[first] * distance[first]
        to_second = distance[second] * distance[second]
        pair = to_first[second]
        merged = numpy.sqrt(
            numpy.maximum(
                ((left + weight) * to_first + (right + weight) * to_second - weight * pair)
                / (joined + weight),
                0.0,
            )
        )
        merged[~alive] = numpy.inf
        merged[first] = merged[second] = numpy.inf

        distance[first, :] = merged
        distance[:, first] = merged
        distance[second, :] = numpy.inf
        distance[:, second] = numpy.inf
        weight[first] = joined
        alive[second] = False
        members[first] = members[first] + members.pop(second)

    groups = [sorted(group) for group in members.values()]
    return sorted(groups, key=lambda group: group[0])


def medoids(matrix, group: list[int], names: list[str], how_many: int = CENTRAL) -> list[str]:
    """The `how_many` members nearest the middle of their own cluster.

    A one-member cluster is its own medoid and its mean distance is zero, which
    is the honest answer rather than a special case.
    """
    import numpy

    block = numpy.asarray(matrix, dtype=numpy.float64)[numpy.ix_(group, group)]
    spread = block.sum(axis=1) / max(1, len(group) - 1)
    order = sorted(range(len(group)), key=lambda index: (float(spread[index]), names[group[index]]))
    return [names[group[index]] for index in order[:how_many]]


def record(directory: Path | None = None, count: int = CLUSTERS) -> list[dict]:
    """The whole grouping, as the rows the tracked file holds."""
    import numpy

    from fractal_wallpapers.palettes import space

    names = library(directory)
    if not names:
        raise ClusterError("the colormap library is empty, so there is nothing to group")
    matrix = numpy.round(space.distances(tuple(names)), PLACES)
    groups = ward(matrix, count)
    return [
        {
            "schema": SCHEMA,
            "kind": METHOD_ROW,
            "maps": len(names),
            "clusters": count,
            "central": CENTRAL,
            "method": METHOD,
        },
        *(
            {
                "schema": SCHEMA,
                "kind": CLUSTER_ROW,
                "cluster": index,
                "size": len(group),
                "central": medoids(matrix, group, names),
                "members": [names[position] for position in group],
            }
            for index, group in enumerate(groups)
        ),
    ]


def record_path(directory: Path | None = None) -> Path:
    """Where the grouping lives: beside the maps it groups."""
    return (Path(directory) if directory is not None else colormap_dir()) / RECORD_NAME


def text_of(rows: list[dict]) -> str:
    """The file's text: one row to a line, the header first."""
    return "".join(json.dumps(row, ensure_ascii=False) + "\n" for row in rows)


def write(rows: list[dict], directory: Path | None = None) -> Path:
    path = record_path(directory)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text_of(rows), encoding="utf-8", newline="\n")
    return path


def read(directory: Path | None = None) -> list[dict]:
    """The committed grouping's rows, or an empty list if it was never written."""
    path = record_path(directory)
    if not path.is_file():
        return []
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line]


def run(directory: Path | None = None, count: int = CLUSTERS) -> dict:
    """Regenerate the grouping and write it. Returns what it wrote, in one line."""
    rows = record(directory, count)
    path = write(rows, directory)
    groups = [row for row in rows if row["kind"] == CLUSTER_ROW]
    return {
        "path": str(path),
        "maps": rows[0]["maps"],
        "clusters": rows[0]["clusters"],
        "sizes": [group["size"] for group in groups],
    }


__all__ = [
    "CENTRAL",
    "CLUSTERS",
    "CLUSTER_ROW",
    "METHOD",
    "METHOD_ROW",
    "PLACES",
    "RECORD_NAME",
    "SCHEMA",
    "ClusterError",
    "library",
    "medoids",
    "read",
    "record",
    "record_path",
    "run",
    "text_of",
    "ward",
    "write",
]
