"""The glance sheets: what a colour cell actually looks like, so an eye can rule on it.

A census table says `dark_muted_lime: offered 3013, picked 0`. It cannot say
whether that is a gap worth closing or a colour nobody should want, and no number
will: *absent* and *rare and fine* are the same row. So the census writes two
pages of pictures and Matt rules from those.

Both land in `scratch/`, which is defined as disposable — they are megabytes of
embedded thumbnails, they are regenerated by re-running the census, and nothing
reads them.

## Sampled, not exhaustive, and it says by how much

A glance sheet is for glancing. Four and a half thousand candidate renders is not
a page anybody looks at, so each cell shows a bounded sample and the header says
what the sample was drawn from. A page that quietly showed the first twenty of a
hundred would read as the whole cell.

The draw is **seeded and stated**, so the same census produces the same page
twice and a reader comparing two sheets is comparing populations rather than
shuffles.

## The sparse sheet shows everything it has

The second page is the opposite policy on purpose. Its whole question is *is
there anything here at all*, and a sample of a cell holding six pictures would
answer it wrong. So the sparse cells are drawn whole, however little they hold —
and a cell holding nothing is printed as an empty row rather than omitted,
because a missing row and an empty one read identically and mean opposite things.
"""

from __future__ import annotations

import html
import random
from pathlib import Path

from fractal_wallpapers.palettes import codebook

#: How many pictures one cell may show on the by-swatch sheet. A glance-sheet
#: number: twelve across a few dozen cells is a page that loads and scrolls.
PER_CELL = 12

#: How many cells the sparse sheet covers, counted up from the least populated.
SPARSE_CELLS = 12

#: The seed the sample is drawn under, so two runs of one census agree.
SAMPLE_SEED = 0

#: Thumbnails are small here — the question is "what colour is this", not "is this
#: a good wallpaper" — and a page of a few hundred has to stay openable.
THUMBNAIL_WIDTH = 200


def _swatch_chip(name: str) -> str:
    """The codebook's own colour for a cell, so the tiles can be compared to it."""
    for entry in codebook.swatches():
        if entry["swatch"] == name:
            red, green, blue = entry["srgb"]
            return f"rgb({red},{green},{blue})"
    return "transparent"


def _tile(row: dict) -> str:
    from fractal_wallpapers.curation import sheet

    source = sheet.thumbnail(Path(row["picture"]), width=THUMBNAIL_WIDTH)
    if not source:
        return ""
    caption = " · ".join(
        str(value)
        for value in (row.get("colormap"), row.get("partition"), row.get("head"))
        if value
    )
    return (
        '<figure class="tile">'
        f'<img loading="lazy" src="{source}" alt="">'
        f"<figcaption>{html.escape(caption)}<br>"
        f'<span class="share">{row["dominant_share"]:.0%} · {row["entropy_bits"]:.1f}b</span>'
        "</figcaption></figure>"
    )


STYLE = """
body { background:#12141a; color:#e8e8ea; font:13px/1.5 system-ui, sans-serif; margin:24px; }
h1 { font-size:20px; margin:0 0 4px; }
p.note { color:#9aa0aa; max-width:62em; }
section { margin:28px 0; }
h2 { font-size:15px; display:flex; align-items:center; gap:10px; margin:0 0 8px; }
.chip { width:30px; height:16px; border-radius:3px; border:1px solid #444; display:inline-block; }
.count { color:#9aa0aa; font-weight:400; }
.grid { display:flex; flex-wrap:wrap; gap:10px; }
.tile { margin:0; width:200px; }
.tile img { width:200px; border-radius:3px; display:block; }
figcaption { color:#9aa0aa; font-size:11px; margin-top:3px; word-break:break-word; }
.share { color:#6f7681; }
.empty { color:#c98b8b; font-style:italic; }
"""


def _page(title: str, note: str, sections: list[str]) -> str:
    return (
        f"<!doctype html><meta charset='utf-8'><title>{html.escape(title)}</title>"
        f"<style>{STYLE}</style><h1>{html.escape(title)}</h1>"
        f"<p class='note'>{note}</p>" + "".join(sections)
    )


def _section(name: str, rows: list[dict], held: int, shown: int) -> str:
    tiles = "".join(_tile(row) for row in rows)
    body = (
        f'<div class="grid">{tiles}</div>'
        if tiles
        else '<div class="empty">nothing in the pool is dominated by this colour</div>'
    )
    counted = f"{held} in the pool" + (f", {shown} shown" if shown < held else "")
    return (
        f'<section><h2><span class="chip" style="background:{_swatch_chip(name)}"></span>'
        f"{html.escape(name)} <span class='count'>{counted}</span></h2>{body}</section>"
    )


def _by_dominant(rows: list[dict]) -> dict[str, list[dict]]:
    cells: dict[str, list[dict]] = {name: [] for name in codebook.names()}
    for row in rows:
        cells[row["dominant"]].append(row)
    return cells


def write(rows: list[dict], directory: Path, seed: int = SAMPLE_SEED) -> dict:
    """Both sheets, from the census's own survival rows. Returns what was written."""
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    candidates = [row for row in rows if row.get("stage") == "survival"]
    cells = _by_dominant(candidates)

    drawn = random.Random(seed)
    sections = []
    for name in codebook.names():
        held = cells[name]
        shown = sorted(drawn.sample(held, min(PER_CELL, len(held))), key=lambda row: row["picture"])
        sections.append(_section(name, shown, len(held), len(shown)))
    everything = directory / "color_census_by_swatch.html"
    everything.write_text(
        _page(
            "Colour census - the candidate pool by dominant swatch",
            f"{len(candidates):,} candidate renders, every one of the 52 cells, at most "
            f"{PER_CELL} shown per cell, sampled under seed {seed}. Each cell's chip is the "
            "codebook colour itself. A cell printed empty is empty.",
            sections,
        ),
        encoding="utf-8",
        newline="\n",
    )

    order = sorted(codebook.names(), key=lambda name: (len(cells[name]), name))
    sparse = order[:SPARSE_CELLS]
    sections = [_section(name, cells[name], len(cells[name]), len(cells[name])) for name in sparse]
    thinnest = directory / "color_census_sparse.html"
    thinnest.write_text(
        _page(
            "Colour census - the sparsest swatches, whole",
            f"The {SPARSE_CELLS} least populated cells of {len(candidates):,} candidate "
            "renders, drawn <strong>whole</strong> rather than sampled: the question here is "
            "whether anything exists at all, and a sample would answer it wrong.",
            sections,
        ),
        encoding="utf-8",
        newline="\n",
    )
    return {
        "by_swatch": str(everything),
        "sparse": str(thinnest),
        "candidates": len(candidates),
        "seed": seed,
        "per_cell": PER_CELL,
        "sparse_cells": {name: len(cells[name]) for name in sparse},
        "empty_cells": sorted(name for name in codebook.names() if not cells[name]),
    }


__all__ = ["PER_CELL", "SAMPLE_SEED", "SPARSE_CELLS", "THUMBNAIL_WIDTH", "write"]
